# -*- coding: utf-8 -*-
"""Games Sales

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ARB4OAnMTc2JCleySuzLal39va6DPAgM
"""

import pandas as pd

data = pd.read_csv('/content/Games Sales - Games (1).csv')

data.head(10)

data.info()

#cek data
data.isna().sum()

#menghapus data terduplikasi
data.duplicated().sum()

#cek data terduplikasi
data[data.duplicated()]

data_cleaned = data.copy()

# convert release to date format = (yyyy-dd-mm)
data_cleaned['Release'] = pd.to_datetime(data_cleaned['Release'])

# change null row in series column by '-'
data_cleaned['Series'] = data_cleaned['Series'].fillna('-')

# remove duplicated dataset
data_cleaned = data_cleaned.drop_duplicates(keep='first')

# check data after drop duplicates 
data_cleaned[data_cleaned.duplicated()]

data_cleaned.info()

# save data_cleaned
data_cleaned.to_csv("Game Sales Cleaned.csv", index=False)
print()

release_sort = data_cleaned.sort_values(by='Release')
games_oldest_newest = pd.concat([release_sort.head(1), release_sort.tail(1)])
games_oldest_newest

import matplotlib.pyplot as plt
import numpy as np

data = pd.read_csv('/content/Game Sales Cleaned.csv')

y = np.array([8, 6, 5, 4, 4])
mylabels = ["Blizzard Entertainment", "Maxis", "Paradox Development Studio", "Valve", "id Software"]

plt.figure(figsize=(6,6))
plt.pie(y, labels = mylabels, autopct='%.1f%%')
plt.title('Most Developed Game by Developer',loc='center', pad=30, fontsize=15, color='blue')

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('/content/Game Sales Cleaned.csv')
y = np.array([19, 8, 7, 6, 5])
mylabels = ["Electronics Arts", "Blizzard Entertainment", "Paradox Development Studio", "Activision"," GT Interactive"]

plt.figure(figsize=(6,6))
plt.pie(y, labels = mylabels, autopct='%.1f%%')
plt.title('Most Game Published by Publisher', loc='center', pad=30, fontsize=15, color='blue')
plt.show()

from pandas.core import series
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
x = ['Minecraft', 'Diablo', 'The Sims', 'Half-Life', 'Warcraft']
y = [33, 26, 24, 21, 19]

for i in range (len(x)):
  plt.text(i, y[i], y[i], ha='center', va='bottom')

bar_colors = ['tab:red', 'tab:blue', 'tab:red', 'tab:orange','tab:green']
ax.bar(x, y, color=bar_colors)

ax.set_xlabel('Series', fontsize=15)
ax.set_ylabel('Sum of sales', fontsize=15)
ax.set_title('Series Based on The Most Sales', loc='center', pad=30, fontsize=15, color='blue')
plt.ylim([0, 40])

plt.show()

from pandas.core import series
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
x = ['Command & Conqueror', 'StarCraft', 'Age of Empires', 'Civilization', 'Resident Evil']
y = [5, 4, 4, 4, 3]

for i in range (len(x)):
  plt.text(i, y[i], y[i], ha='center', va='bottom')

bar_colors = ['tab:red', 'tab:blue', 'tab:red', 'tab:orange','tab:green']
ax.bar(x, y, color=bar_colors)

ax.set_xlabel('Series', fontsize=15)
ax.set_ylabel('Sum of Games', fontsize=15)
ax.set_title('Series Based on The Most Games', loc='center', pad=30, fontsize=15, color='blue')
plt.ylim([0, 8])

plt.show()